# .github/workflows/benchmarks.yml
name: Validate-Benchmarks

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: run-benchmarks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-benchmarks:
    runs-on: Benchmarking

    env:
      SKIP_BENCHMARKS: "0"
      AUTO_COMMIT_WEIGHTS: "1"

    steps:
      # ──────────────────────────────────────────────────────────────────
      - name: Check out PR branch
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install GitHub CLI
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # (1) — first skip‑label check
      - name: Check skip label
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} \
                         --repo "${{ github.repository }}" \
                         --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "skip-validate-benchmarks label found — skipping benchmarks."
            echo "SKIP_BENCHMARKS=1" >> "$GITHUB_ENV"
          fi

      - name: Install system dependencies
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev protobuf-compiler

      # (2)
      - name: Check skip label
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} \
                         --repo "${{ github.repository }}" \
                         --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "skip-validate-benchmarks label found — skipping benchmarks."
            echo "SKIP_BENCHMARKS=1" >> "$GITHUB_ENV"
          fi

      - name: Install Rust toolchain
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      # (3)
      - name: Check skip label
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} \
                         --repo "${{ github.repository }}" \
                         --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "skip-validate-benchmarks label found — skipping benchmarks."
            echo "SKIP_BENCHMARKS=1" >> "$GITHUB_ENV"
          fi

      - name: Cache Rust build
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        uses: Swatinem/rust-cache@v2
        with:
          key: bench-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true

      # (4)
      - name: Check skip label
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} \
                         --repo "${{ github.repository }}" \
                         --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "skip-validate-benchmarks label found — skipping benchmarks."
            echo "SKIP_BENCHMARKS=1" >> "$GITHUB_ENV"
          fi

      - name: Build node with benchmarks
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          cargo build --profile production -p node-subtensor --features runtime-benchmarks

      # (5)
      - name: Check skip label
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} \
                         --repo "${{ github.repository }}" \
                         --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "skip-validate-benchmarks label found — skipping benchmarks."
            echo "SKIP_BENCHMARKS=1" >> "$GITHUB_ENV"
          fi

      - name: Run & validate benchmarks
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          chmod +x scripts/benchmark_action.sh
          scripts/benchmark_action.sh

      # (6) — final check after run
      - name: Check skip label after run
        if: ${{ env.SKIP_BENCHMARKS != '1' }}
        run: |
          labels=$(gh pr view ${{ github.event.pull_request.number }} \
                         --repo "${{ github.repository }}" \
                         --json labels --jq '.labels[].name')
          if echo "$labels" | grep -q "skip-validate-benchmarks"; then
            echo "skip-validate-benchmarks label was found — but benchmarks already ran."
          fi
