name: Try Runtime

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-devnet:
    name: check devnet
    if: github.base_ref != 'main'
    runs-on: SubtensorCI
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "try-runtime"

      - name: Run Try Runtime Checks
        uses: "paritytech/try-runtime-gha@v0.1.0"
        with:
          runtime-package: "node-subtensor-runtime"
          node-uri: "wss://dev.chain.opentensor.ai:443"
          checks: "all"
          extra-args: "--disable-spec-version-check --no-weight-warnings"

  check-testnet:
    name: check testnet
    if: github.base_ref != 'main'
    runs-on: SubtensorCI
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: "try-runtime"

      - name: Run Try Runtime Checks
        uses: "paritytech/try-runtime-gha@v0.1.0"
        with:
          runtime-package: "node-subtensor-runtime"
          node-uri: "wss://archive.dev.opentensor.ai:8443"
          checks: "all"
          extra-args: "--disable-spec-version-check --no-weight-warnings"

  check-finney:
    name: check finney
    # if: github.base_ref == 'testnet' || github.base_ref == 'devnet' || github.base_ref == 'main'
    runs-on: SubtensorCI
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Utilize Shared Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          key: try-runtime
          cache-on-failure: true

      - name: Run Try Runtime Checks
        uses: "paritytech/try-runtime-gha@v0.1.0"
        with:
          runtime-package: "node-subtensor-runtime"
          node-uri: "wss://archive.dev.opentensor.ai:443"
          checks: "all"
          extra-args: "--disable-spec-version-check --no-weight-warnings"
